name: CI

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This step checks out our repository code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7  # Adjust to latest Terraform version

      - name: Initialize Terraform
        run: terraform init  # Initialize Terraform configuration
        working-directory: ./terraform/baseinfra #just a trial not final working directory code.

      - name: Validate Terraform
        run: terraform validate  # Validate Terraform code
        working-directory: ./terraform/baseinfra #${{github.event.inputs.tfpath}} 

      - name: Notify team
        run: echo "CI/CD workflow  run complete."  #Notification

